## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv('../Weather_Database/WeatherPy_Database.csv')
city_data_df.head(5)

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Yellowknife,62.4560,-114.3525,66.72,55,40,scattered clouds,CA,2021-08-13 02:51:41
1,1,Vila Franca Do Campo,37.7167,-25.4333,73.81,79,64,broken clouds,PT,2021-08-13 02:54:46
2,2,Nikolskoye,59.7035,30.7861,64.29,93,100,light rain,RU,2021-08-13 02:54:46
3,3,Jamestown,42.0970,-79.2353,74.71,88,1,clear sky,US,2021-08-13 02:54:46
4,4,Kavieng,-2.5744,150.7967,81.64,78,100,light rain,PG,2021-08-13 02:54:47

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
4,4,Kavieng,-2.5744,150.7967,81.64,78,100,light rain,PG,2021-08-13 02:54:47
8,8,Iberia,29.9502,-91.7507,77.97,83,100,overcast clouds,US,2021-08-13 02:54:48
9,9,Butaritari,3.0707,172.7902,81.97,76,36,light rain,KI,2021-08-13 02:54:48
14,14,Buala,-8.1450,159.5921,76.46,91,100,moderate rain,SB,2021-08-13 02:54:50
17,17,Bansud,12.8650,121.4564,86.65,67,85,overcast clouds,PH,2021-08-13 02:54:51
29,29,Meulaboh,4.1363,96.1285,80.42,80,99,overcast clouds,ID,2021-08-13 02:54:55
30,30,Hithadhoo,-0.6000,73.0833,80.24,77,100,moderate rain,MV,2021-08-13 02:54:56
32,32,Volsk,52.0333,47.3833,75.74,27,39,scattered clouds,RU,2021-08-13 02:54:56
36,36,Atuona,-9.8000,-139.0333,77.79,71,55,broken clouds,PF,2021-08-13 02:54:58
40,40,Mauganj,24.6833,81.8833,83.71,72,77,broken clouds,IN,2021-08-13 02:54:59

In [10]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0    254
City          254
Lat           254
Lng           254
Max Temp      254
Humidity      254
Cloudiness    254
Wind Speed    254
Country       254
Date          254
dtype: int64

In [ ]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [11]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

KeyError: "['Current Description'] not in index"

In [ ]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

In [ ]:
# 7. Drop the rows where there is no Hotel Name.

In [ ]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure